// arduino pinout

#define BAT_FAN_ENABLE 34
#define MOT_FAN_ENABLE 32
#define LCD_RS         53
#define LCD_ENABLE     51
#define LCD_D4         46
#define LCD_D5         47
#define LCD_D6         48
#define LCD_D7         49
#define BUTTON_1        6
#define BUTTON_2        5
#define BUTTON_3        8
#define BUTTON_4        7
#define BUTTON_5        9
#define MOTOR_SOLENOID 40
#define CONTACTOR_SOLENOID  36
#define BOOST_CONTROL  11
#define BAT_V_SENSOR A15
#define FC_V_SENSOR A14
